### ISSUE TITLE
default for target value in JSON?

### ISSUE THREAD

**Issue by sftcd** [sftcd/wkesni#10]
In -02 we say that the targetName attribute of the RR can be provided by the target element of an endpoints array element with a default of "."

That's fine, but confuses me for cases when the port != 443.

When port != 443 testing (and @davidben advice:-) showed that the hostname of the server and not "." was the targetName value that should be the default, but I don't claim to understand why TBH, it just worked (for chromium based browsers though not yet FF).

I think that may mean that we should say that the default targetName to use is "." iff port == 443 but otherwise the hostname from $ORIGIN if port != 443

**Comment by bemasc** [comment]
Specifically, the line I linked to rejects the HTTPS record if it specifies a port AND that port is different from the one in the URL.

**Comment by sftcd** [comment]
Right but the port is in the URL in the case above. When I used "." as target for that specific HTTPS RR, chrome did not work.

**Comment by sftcd** [comment]
I think we can close this one too - agreed?

**Comment by richsalz** [comment]
agree to close
