### ISSUE TITLE
The URL itself

### ISSUE THREAD

**Issue by sftcd** [sftcd/wkesni#12]
draft-03 says to access https://$ORIGIN/.well-known/origin-svcb for the JSON. I think that needs to go back to https://$ORIGIN/.well-known/origin-svcb/$ORIGIN in order to more easily support a DocRoot shared by multiple origins.

**Comment by richsalz** [comment]
Is that common?  I didn't know that.  I'm fine with either URL.

**Comment by bemasc** [comment]
That's only needed if the different origins have distinct ECH configurations, right?  That seems strange, since if the DocRoot is shared then the origins are likely served from a shared server.

**Comment by sftcd** [comment]
yeah, probably an odd setup, but one I use in my test setup - I could  probably avoid doing that if better to stick with the URL from draft-03 but figured worth pondering anyway. I've no idea if it'd be needed otherwise.

**Comment by sftcd** [comment]
I think it makes sense to close this one now - we made a decision for draft-04 so if we do want further discussion of the URL to use that'll be better based on more up to date text.
