### ISSUE TITLE
more clarity wrt alias records needed 

### ISSUE THREAD

**Issue by sftcd** [sftcd/wkesni#17]
Part of @martinthomson's [review](https://mailarchive.ietf.org/arch/msg/tls/fOMXBXX62UmqZeR9wfs-qwkX9sU/)

> The design for publishing alias records is something I cannot decipher at all.
> There's a description of the field, but no real supporting material for that.

Fair comment. Needs fixing.

**Comment by richsalz** [comment]
I believe that with the revised descriptions of `endpoints` and the pointers to the `AliasMode` entry in the SVCB RFC, this should be closed.
