### ISSUE TITLE
Do we need "generatedat" ?

### ISSUE THREAD

**Issue by richsalz** [sftcd/wkesni#26]
The doc talks about "regeninterval" which is defined as the number of seconds are which the value retrieved may be changed. Don't we need to know when the value was generaed?  Should regeninterval be "notafter", some kind of timestamp?

**Comment by bemasc** [comment]
I don't think we need a precise expiration time like "notafter".  A precise expiration time like that might be more conventional than the current design, but I think it's too stringent for this use case.  For WKECH, the ZF cannot afford to fail open (removing the HTTPS records) or closed (removing the IP records).  However, it can safely "stretch" the lifetime of the HTTPS records, thanks to ECH's fallback connection behavior.

If we accept that we are sometimes going to stretch the TTL, then it seems logical to avoid an explicit expiration time, and instead speak about the intended update frequency.  This makes it clear that the origin must tolerate some amount of version skew, and gives operational flexibility to avoid unreasonable update frequencies.

**Comment by richsalz** [comment]
Okay, that convinces me.  Do we need to put that wording in the draft somewhere?
