### ISSUE TITLE
IANA registry location

### ISSUE THREAD

**Issue by sftcd** [sftcd/wkesni#7]
IANA folk took a look at draft -01 and asked: 

> The IANA Considerations section says, "If approved, this specification requests the creation of an IANA registry named "JSON HTTP Origin Info"."
> Where should this new registry be located? Should it be added to an existing registry page? If it needs a new page, does it also need a new category at http://www.iana.org/protocols (and if so, should the page and the category have the same name)?

As things proceed we should answer that question for whatever design we end up with.

**Comment by richsalz** [comment]
We don't need a new category, this is just an "assignment". It would either go on the "other" SVCB page https://www.iana.org/assignments/dns-svcb/dns-svcb.xhtml (although that's not a perfect fit), or it could go on a new page but in that same `dns-svcb` directory, such as `dns-svcb/json-svcb.xml`. I added commit d4b184a in #29 to propose the latter and will close this once that PR is merged.
